FIND_PATH(CPGPLOT_INCLUDE_DIR cpgplot.h /star/include)

FIND_LIBRARY(CPGPLOT_LIBRARIES_PGPLOT NAMES pgplot PATHS
    /star/lib /sw/lib/pgplot /usr/X11R6/lib)
FIND_LIBRARY(CPGPLOT_LIBRARIES_CPGPLOT NAMES cpgplot PATHS
    /star/lib /sw/lib/pgplot /usr/X11R6/lib)
FIND_LIBRARY(CPGPLOT_LIBRARIES_X11 NAMES X11 PATHS
    /star/lib /sw/lib/pgplot /usr/X11R6/lib)

set(CPGPLOT_LIBRARIES
    ${CPGPLOT_LIBRARIES_PGPLOT}
    ${CPGPLOT_LIBRARIES_CPGPLOT}
    ${CPGPLOT_LIBRARIES_X11}
    )



if (CPGPLOT_INCLUDE_DIR AND CPGPLOT_LIBRARIES)
    set (CPGPLOT_FOUND true)
endif(CPGPLOT_INCLUDE_DIR AND CPGPLOT_LIBRARIES)

if (CPGPLOT_FOUND)
    if (NOT CPGPLOT_FIND_QUIETLY)
        message(STATUS "Found cpgplot: ${CPGPLOT_LIBRARIES}")
    endif(NOT CPGPLOT_FIND_QUIETLY)
else (CPGPLOT_FOUND)
   if (CPGPLOT_FIND_REQUIRED)
      message(FATAL_ERROR "Could not find cpgplot")
    endif(CPGPLOT_FIND_REQUIRED)
endif(CPGPLOT_FOUND) 
