FIND_PATH(SRWPHOTOM_INCLUDE_DIR srwphotom.h /home/astro/phrfbf/build/include)

FIND_LIBRARY(SRWPHOTOM_LIBRARIES NAMES photom PATHS /home/astro/phrfbf/build/lib64 NO_DEFAULT_PATH)

if (SRWPHOTOM_INCLUDE_DIR AND SRWPHOTOM_LIBRARIES)
    set (SRWPHOTOM_FOUND true)
endif(SRWPHOTOM_INCLUDE_DIR AND SRWPHOTOM_LIBRARIES)

if (SRWPHOTOM_FOUND)
    if (NOT SRWPHOTOM_FIND_QUIETLY)
        message(STATUS "Found srwphotom: ${SRWPHOTOM_LIBRARIES}")
    endif(NOT SRWPHOTOM_FIND_QUIETLY)
else (SRWPHOTOM_FOUND)
   if (SRWPHOTOM_FIND_REQUIRED)
      message(FATAL_ERROR "Could not find srwphotom")
    endif(SRWPHOTOM_FIND_REQUIRED)
endif(SRWPHOTOM_FOUND) 
