SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} $ENV{HOME}/cmake_packages)
FIND_PACKAGE(mysql QUIET)


FIND_PATH(MYSQLPP_INCLUDES mysql++.h 
    PATHS 
    /opt/local/include
    $ENV{HOME}/build/include
    PATH_SUFFIXES
    mysql++
    )

FIND_LIBRARY(MYSQLPP_ONLY_LIBRARIES NAMES mysqlpp PATHS
    /opt/local/lib
    $ENV{HOME}/build/lib
    )




if (MYSQLPP_INCLUDES AND MYSQLPP_ONLY_LIBRARIES AND MYSQL_FOUND)
    set (MYSQLPP_FOUND true)
endif(MYSQLPP_INCLUDES AND MYSQLPP_ONLY_LIBRARIES AND MYSQL_FOUND)

if (MYSQLPP_FOUND)
    set(MYSQLPP_INCLUDE_DIR ${MYSQL_INCLUDE_DIR} ${MYSQLPP_INCLUDES})
    set(MYSQLPP_LIBRARIES ${MYSQL_LIBRARIES} ${MYSQLPP_ONLY_LIBRARIES})
    if (NOT MYSQLPP_FIND_QUIETLY)
        message(STATUS "Found mysqlpp: ${MYSQLPP_LIBRARIES}")
    endif(NOT MYSQLPP_FIND_QUIETLY)
else (MYSQLPP_FOUND)
   if (MYSQLPP_FIND_REQUIRED)
      message(FATAL_ERROR "Could not find mysqlpp")
    endif(MYSQLPP_FIND_REQUIRED)
endif(MYSQLPP_FOUND) 
