FIND_PATH(GENERATENOISE_INCLUDE_DIR generateNoise.h /home/astro/phrfbf/build/include)

FIND_LIBRARY(GENERATENOISE_LIBRARIES NAMES colouredNoise PATH /home/astro/phrfbf/build/lib)

if (GENERATENOISE_INCLUDE_DIR AND GENERATENOISE_LIBRARIES)
    set (GENERATENOISE_FOUND true)
endif(GENERATENOISE_INCLUDE_DIR AND GENERATENOISE_LIBRARIES)

if (GENERATENOISE_FOUND)
    if (NOT GENERATENOISE_FIND_QUIETLY)
        message(STATUS "Found generateNoise: ${GENERATENOISE_LIBRARIES}")
    endif(NOT GENERATENOISE_FIND_QUIETLY)
else (GENERATENOISE_FOUND)
   if (GENERATENOISE_FIND_REQUIRED)
      message(FATAL_ERROR "Could not find generateNoise")
    endif(GENERATENOISE_FIND_REQUIRED)
endif(GENERATENOISE_FOUND) 
