FIND_PACKAGE(sqlite REQUIRED)

FIND_PATH(SQLITEWRAPPED_INCLUDE_DIR libsqlitewrapped.h
    PATHS 
    /opt/local/include
    $ENV{HOME}/build/include
    )

FIND_LIBRARY(SQLITEWRAPPED_LIBRARIES NAMES sqlitewrapped PATHS
    $ENV{HOME}/build/lib
    /opt/local/lib
    /usr/lib64
    )



if (SQLITEWRAPPED_INCLUDE_DIR AND SQLITEWRAPPED_LIBRARIES)
    set (SQLITEWRAPPED_FOUND true)
endif(SQLITEWRAPPED_INCLUDE_DIR AND SQLITEWRAPPED_LIBRARIES)

set(SQLITEWRAPPED_INCLUDE_DIR ${SQLITEWRAPPED_INCLUDE_DIR} ${SQLITE_INCLUDE_DIR})
set(SQLITEWRAPPED_LIBRARIES ${SQLITEWRAPPED_LIBRARIES} ${SQLITE_LIBRARIES})


if (SQLITEWRAPPED_FOUND)
    if (NOT SQLITEWRAPPED_FIND_QUIETLY)
        message(STATUS "Found sqlitewrapped: ${SQLITEWRAPPED_LIBRARIES}")
    endif(NOT SQLITEWRAPPED_FIND_QUIETLY)
else (SQLITEWRAPPED_FOUND)
   if (SQLITEWRAPPED_FIND_REQUIRED)
      message(FATAL_ERROR "Could not find sqlitewrapped")
    endif(SQLITEWRAPPED_FIND_REQUIRED)
endif(SQLITEWRAPPED_FOUND) 
